#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1
NAME=pia-wireguard-watchdog
PROG=/usr/sbin/pia-wireguard-watchdog

start_service() {
	local enabled

	config_load pia-wireguard
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn 3600 5 5
	procd_set_param file /etc/config/pia-wireguard
	procd_set_param file /etc/pia-wireguard.secrets
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger pia-wireguard
	procd_add_interface_trigger "interface.*" lan /etc/init.d/pia-wireguard-watchdog restart
}

